# GitHub Pages Configuration
# This file helps configure the website for GitHub Pages deployment

# Jekyll configuration (optional - GitHub Pages uses Jekyll by default)
# If you want to disable Jekyll processing, create a .nojekyll file instead

# For static HTML sites, you typically don't need this file
# But it's included for reference and future customization

# Site settings
title: "OS³: Open Source Security Studio"
description: "Educational cybersecurity platform for hands-on learning"
url: "https://jwilliamsresearch.github.io"
baseurl: "/newmanCyberLab/os3-website"  # Adjust based on your repository structure

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - assets/images/README.md

# Include files that start with underscore
include:
  - _headers
  - _redirects

# Plugin settings (if using Jekyll)
plugins:
  - jekyll-sitemap
  - jekyll-feed
